 const TaskActionConstants = {
  ACTION_ADD : "ACTION_ADD",
  ACTION_EDIT : "ACTION_EDIT",
  ACTION_DELETE : "ACTION_DELETE",
  ACTION_RELOAD : "ACTION_RELOAD",
  ACTION_COMPLETE: "ACTION_COMPLETE",
  ACTION_UPDATEELAPSEDTASK: "ACTION_UPDATEELAPSEDTASK",
  ACTION_SETINPROGRESS: "ACTION_SETINPROGRESS"
}

export default TaskActionConstants;
