const TimerActionConstants = {
 ACTION_TIMERSTART: "ACTION_TIMERSTART",
 ACTION_TIMERRESET: "ACTION_TIMERRESET",
 ACTION_TIMERSTOP: "ACTION_TIMERSTOP",
 ACTION_ADDCONFIG: "ACTION_ADDCONFIG"
}

export default TimerActionConstants;
